// Major Indian cities for autocomplete
export const INDIAN_CITIES = [
    // Metro Cities
    'Mumbai, Maharashtra',
    'Delhi',
    'Bengaluru, Karnataka',
    'Hyderabad, Telangana',
    'Chennai, Tamil Nadu',
    'Kolkata, West Bengal',
    'Ahmedabad, Gujarat',
    'Pune, Maharashtra',

    // State Capitals & Major Cities
    'Jaipur, Rajasthan',
    'Lucknow, Uttar Pradesh',
    'Kanpur, Uttar Pradesh',
    'Nagpur, Maharashtra',
    'Indore, Madhya Pradesh',
    'Bhopal, Madhya Pradesh',
    'Visakhapatnam, Andhra Pradesh',
    'Patna, Bihar',
    'Vadodara, Gujarat',
    'Ludhiana, Punjab',
    'Agra, Uttar Pradesh',
    'Nashik, Maharashtra',
    'Varanasi, Uttar Pradesh',
    'Srinagar, Jammu and Kashmir',
    'Chandigarh',
    'Coimbatore, Tamil Nadu',
    'Madurai, Tamil Nadu',
    'Kochi, Kerala',
    'Thiruvananthapuram, Kerala',
    'Guwahati, Assam',
    'Bhubaneswar, Odisha',
    'Raipur, Chhattisgarh',
    'Ranchi, Jharkhand',
    'Dehradun, Uttarakhand',
    'Shimla, Himachal Pradesh',
    'Jammu, Jammu and Kashmir',
    'Amritsar, Punjab',
    'Jodhpur, Rajasthan',
    'Udaipur, Rajasthan',
    'Mysuru, Karnataka',
    'Mangaluru, Karnataka',
    'Hubli, Karnataka',
    'Vijayawada, Andhra Pradesh',
    'Guntur, Andhra Pradesh',
    'Tirupati, Andhra Pradesh',
    'Salem, Tamil Nadu',
    'Tiruchirappalli, Tamil Nadu',
    'Tirunelveli, Tamil Nadu',
    'Kozhikode, Kerala',
    'Thrissur, Kerala',
    'Kannur, Kerala',
    'Cuttack, Odisha',
    'Rourkela, Odisha',
    'Gwalior, Madhya Pradesh',
    'Jabalpur, Madhya Pradesh',
    'Ujjain, Madhya Pradesh',
    'Rajkot, Gujarat',
    'Surat, Gujarat',
    'Bhavnagar, Gujarat',
    'Jamnagar, Gujarat',
    'Aurangabad, Maharashtra',
    'Solapur, Maharashtra',
    'Kolhapur, Maharashtra',
    'Dhanbad, Jharkhand',
    'Jamshedpur, Jharkhand',
    'Gaya, Bihar',
    'Bhagalpur, Bihar',
    'Muzaffarpur, Bihar',
    'Gorakhpur, Uttar Pradesh',
    'Allahabad, Uttar Pradesh',
    'Meerut, Uttar Pradesh',
    'Bareilly, Uttar Pradesh',
    'Aligarh, Uttar Pradesh',
    'Moradabad, Uttar Pradesh',
    'Saharanpur, Uttar Pradesh',
    'Gurgaon, Haryana',
    'Faridabad, Haryana',
    'Rohtak, Haryana',
    'Jalandhar, Punjab',
    'Patiala, Punjab',
    'Bathinda, Punjab',
    'Ajmer, Rajasthan',
    'Bikaner, Rajasthan',
    'Kota, Rajasthan',
    'Alwar, Rajasthan',
    'Siliguri, West Bengal',
    'Durgapur, West Bengal',
    'Asansol, West Bengal',
    'Gangtok, Sikkim',
    'Imphal, Manipur',
    'Aizawl, Mizoram',
    'Kohima, Nagaland',
    'Shillong, Meghalaya',
    'Agartala, Tripura',
    'Itanagar, Arunachal Pradesh',
    'Dispur, Assam',
    'Port Blair, Andaman and Nicobar Islands',
    'Puducherry',
    'Panaji, Goa',
    'Daman',
    'Silvassa, Dadra and Nagar Haveli',
];
